groups:
  - name: app.rules
    rules:
      - alert: MyAppUnhealthy
        expr: kube_deployment_status_replicas_unavailable{deployment="myapp"} > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MyApp is unhealthy"
          description: "Some replicas of myapp are unavailable."
