apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollback-webhook
  template:
    metadata:
      labels:
        app: rollback-webhook
    spec:
      containers:
        - name: rollback-webhook
          image: <user_name>/rollback-webhook:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rollback-webhook
spec:
  selector:
    app: rollback-webhook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
